version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: sg-manager-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: sgmanager
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - sg-manager-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/sgmanager --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Enhanced Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: sg-manager-api
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - PORT=8081
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/sgmanager?authSource=admin
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-key}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - MAIL_HOST=${MAIL_HOST:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./logs:/app/logs
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - sg-manager-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Web Server (Nginx)
  frontend:
    image: nginx:alpine
    container_name: sg-manager-frontend
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - sg-manager-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
    driver: local

networks:
  sg-manager-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
