version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: sgmanager-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: sgmanager
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - sgmanager-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sgmanager-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongodb:27017/sgmanager?authSource=admin
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - JWT_SECRET=${JWT_SECRET:-mySecretKey}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - MAIL_HOST=${MAIL_HOST:-smtp.gmail.com}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@sgmanager.com}
    depends_on:
      - mongodb
    networks:
      - sgmanager-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sgmanager-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - sgmanager-network

volumes:
  mongodb_data:

networks:
  sgmanager-network:
    driver: bridge
