version: '3.8'

services:
  # Enhanced Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: sg-manager-api
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - PORT=8081
      - AWS_REGION=us-east-1
    volumes:
      - ~/.aws:/root/.aws:ro
    networks:
      - sg-manager-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Web Server
  frontend:
    image: nginx:alpine
    container_name: sg-manager-frontend
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - sg-manager-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  sg-manager-network:
    driver: bridge
